# Generated by Django 4.1 on 2022-12-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitedetail",
            old_name="descrition_header",
            new_name="description_header",
        ),
    ]
