# Generated by Django 4.1 on 2022-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_descrition_header_sitedetail_description_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
