# Generated by Django 4.1 on 2022-12-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_doctor_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="overview",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(blank=True, max_length=60, null=True)),
                ("degree", models.CharField(blank=True, max_length=60, null=True)),
                ("start_year", models.CharField(blank=True, max_length=60, null=True)),
                ("end_year", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(blank=True, max_length=60, null=True)),
                ("degree", models.CharField(blank=True, max_length=60, null=True)),
                ("start_year", models.CharField(blank=True, max_length=60, null=True)),
                ("end_year", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=260, null=True),
                ),
                ("month", models.CharField(blank=True, max_length=60, null=True)),
                ("year", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
    ]
