# Generated by Django 4.1 on 2022-12-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_doctor_overview_specialization_services_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="doctor/clinic")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctor"
                    ),
                ),
            ],
        ),
    ]
