# Generated by Django 4.1 on 2022-12-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_doctorimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
    ]
