# Generated by Django 4.1 on 2022-12-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_experience_degree"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="qualification",
            new_name="type",
        ),
    ]
