# Generated by Django 4.1 on 2022-12-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_doctorimage_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="home.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialization",
                to="home.doctor",
            ),
        ),
    ]
