# Generated by Django 4.1 on 2022-12-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_hospital_remove_doctorimage_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="opening_timing",
            field=models.CharField(default="hamesha khula rehta hai", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="price",
            field=models.PositiveIntegerField(default=440),
            preserve_default=False,
        ),
    ]
