# Generated by Django 4.1 on 2022-12-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_hospital_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="opening_timing",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
