# Generated by Django 4.1 on 2022-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_doctor_message_link_doctor_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="video_link",
            field=models.CharField(default="google.com", max_length=30),
            preserve_default=False,
        ),
    ]
