# Generated by Django 4.1 on 2022-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_doctor_friday_doctor_monday_doctor_saturday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="friday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="monday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="saturday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="sunday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="thursday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="tuesday",
            field=models.CharField(default="closed", max_length=30),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="wednesday",
            field=models.CharField(default="closed", max_length=30),
        ),
    ]
