# Generated by Django 4.1 on 2022-12-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_doctor_friday_alter_doctor_monday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("phone", models.CharField(max_length=13)),
                ("email", models.CharField(max_length=30)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
    ]
