# Generated by Django 4.1 on 2022-12-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="type",
            new_name="qualification",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="opening_timing",
        ),
    ]
