# Generated by Django 4.1 on 2022-12-24 19:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_rename_type_doctor_qualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="slug-default", editable=False, populate_from="name"
            ),
            preserve_default=False,
        ),
    ]
