# Generated by Django 4.1 on 2022-12-24 19:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_doctor_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="speciality",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="None",
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
