# Generated by Django 4.1 on 2022-12-24 19:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_hospital_slug_speciality_slug_alter_doctor_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="doctor/images")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="home.doctor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Enquire",
        ),
        migrations.AlterField(
            model_name="speciality",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
