# Generated by Django 4.1 on 2022-12-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_sitedetail_footer_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="hospital"),
        ),
    ]
